//! Guest-side SDK for mcgateway WASM merge UDFs.
//!
//! A user writes:
//!
//! ```ignore
//! use mcgateway_sdk::{merge_fn, Entry, MergeResult, Status};
//!
//! #[merge_fn(required_flags = "t")]
//! pub fn last_n_wins(entries: &[Entry<'_>]) -> MergeResult {
//!     entries
//!         .iter()
//!         .enumerate()
//!         .filter(|(_, e)| e.status == Status::Hit)
//!         .filter_map(|(i, e)| e.t.map(|t| (i, t)))
//!         .max_by_key(|(_, t)| *t)
//!         .map_or(MergeResult::Miss, |(i, _)| MergeResult::Winner(i))
//! }
//! ```
//!
//! The `#[merge_fn]` macro emits the ABI exports (`mcgw_alloc`,
//! `mcgw_dealloc`, `mcgw_merge`, `mcgw_abi_version`, optional
//! `mcgw_required_flags`) so the guest crate is a drop-in `cdylib`
//! targetable at `wasm32-wasip1`.
//!
//! This crate is `no_std`; user crates may be either `std` or `no_std`
//! because the exports do not depend on the surrounding runtime.
//! The `alloc` crate is required and provides the guest heap.

#![no_std]

extern crate alloc;

use alloc::vec::Vec;

pub use mcgateway_sdk_macros::merge_fn;

/// Wire-format version understood by this SDK. Must match the host's
/// `mcgateway_wasm_host::ABI_VERSION`; the host refuses to load a
/// module whose `mcgw_abi_version` does not match.
pub const ABI_VERSION: u32 = 1;

/// Size of a single entry record on the wire. See the host crate's
/// `ENTRY_SIZE` for the field layout.
pub const ENTRY_SIZE: usize = 48;

/// Classification the gateway attaches to each pool response before the
/// merge sees it.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Status {
    Hit,
    Miss,
    Error,
}

/// A single pool's response projected into a view the merge can read.
///
/// All borrowed fields point into the entry buffer the host wrote in
/// guest linear memory. The buffer is live for the duration of
/// `mcgw_merge`; merges must not stash `Entry` references beyond that
/// call.
#[derive(Clone, Debug)]
pub struct Entry<'a> {
    pub key: &'a [u8],
    pub pool: &'a str,
    pub status: Status,
    pub t: Option<i64>,
    pub value: Option<&'a [u8]>,
    pub line: Option<&'a [u8]>,
}

/// What a merge decided. Mirrors `mcgateway_core::MergeResult` on the
/// host side; duplicated so guest crates never pull in host-only deps.
#[derive(Debug)]
pub enum MergeResult {
    Winner(usize),
    Synthesized(Vec<u8>),
    Miss,
}

/// Runtime helpers invoked by code generated by `#[merge_fn]`. These
/// are the stable entry points the macro expands to; they are public so
/// the expansion can name them, but users should not call them
/// directly.
///
/// The casts from `usize` to `u32` are safe on the only target that
/// matters (`wasm32-*`, where `usize == u32`). Building the SDK for the
/// host makes those casts lossy in theory; we silence the lint here
/// rather than forcing `try_from` on every wasm pointer operation.
#[doc(hidden)]
#[allow(clippy::cast_possible_truncation)]
pub mod __rt {
    use super::{Entry, MergeResult, Status, ENTRY_SIZE};
    use alloc::alloc::{alloc, dealloc, Layout};
    use alloc::vec::Vec;
    use core::ptr;
    use core::slice;

    fn layout(size: u32, align: u32) -> Layout {
        let size = size as usize;
        let align = (align as usize).max(1);
        Layout::from_size_align(size.max(1), align).expect("bad alloc layout")
    }

    /// # Safety
    /// The host calls this with `size` and `align` matching a later
    /// `mcgw_dealloc` call. Misuse is a host-side bug.
    #[inline]
    #[must_use]
    pub unsafe fn alloc_raw(size: u32, align: u32) -> u32 {
        unsafe { alloc(layout(size, align)) as usize as u32 }
    }

    /// # Safety
    /// `ptr`, `size`, and `align` must match an earlier `mcgw_alloc`.
    #[inline]
    pub unsafe fn dealloc_raw(ptr: u32, size: u32, align: u32) {
        if ptr == 0 {
            return;
        }
        unsafe { dealloc(ptr as usize as *mut u8, layout(size, align)) }
    }

    #[inline]
    unsafe fn read_u32(p: *const u8, off: usize) -> u32 {
        unsafe { ptr::read_unaligned(p.add(off).cast::<u32>()) }
    }

    #[inline]
    unsafe fn read_i64(p: *const u8, off: usize) -> i64 {
        unsafe { ptr::read_unaligned(p.add(off).cast::<i64>()) }
    }

    /// Decode the host-written entries buffer into a `Vec<Entry<'_>>`
    /// with the lifetime of the buffer itself. Callers must not retain
    /// the returned slice past the `mcgw_merge` return.
    ///
    /// # Safety
    /// `ptr` and `count` must have been produced by the host codec.
    #[must_use]
    pub unsafe fn decode_entries<'a>(ptr: u32, count: u32) -> Vec<Entry<'a>> {
        if count == 0 {
            return Vec::new();
        }
        let base = ptr as usize as *const u8;
        let mut v = Vec::with_capacity(count as usize);
        for i in 0..count as usize {
            let rec = unsafe { base.add(i * ENTRY_SIZE) };
            let key_ptr = unsafe { read_u32(rec, 0) };
            let key_len = unsafe { read_u32(rec, 4) };
            let pool_ptr = unsafe { read_u32(rec, 8) };
            let pool_len = unsafe { read_u32(rec, 12) };
            let value_ptr = unsafe { read_u32(rec, 16) };
            let value_len = unsafe { read_u32(rec, 20) };
            let line_ptr = unsafe { read_u32(rec, 24) };
            let line_len = unsafe { read_u32(rec, 28) };
            let status = match unsafe { read_u32(rec, 32) } {
                0 => Status::Hit,
                1 => Status::Miss,
                _ => Status::Error,
            };
            let t_present = unsafe { read_u32(rec, 36) } != 0;
            let t_raw = unsafe { read_i64(rec, 40) };

            let key =
                unsafe { slice::from_raw_parts(key_ptr as usize as *const u8, key_len as usize) };
            let pool_bytes =
                unsafe { slice::from_raw_parts(pool_ptr as usize as *const u8, pool_len as usize) };
            let pool = core::str::from_utf8(pool_bytes).unwrap_or("");
            let value = if value_ptr == 0 {
                None
            } else {
                Some(unsafe {
                    slice::from_raw_parts(value_ptr as usize as *const u8, value_len as usize)
                })
            };
            let line = if line_ptr == 0 {
                None
            } else {
                Some(unsafe {
                    slice::from_raw_parts(line_ptr as usize as *const u8, line_len as usize)
                })
            };

            v.push(Entry {
                key,
                pool,
                status,
                t: if t_present { Some(t_raw) } else { None },
                value,
                line,
            });
        }
        v
    }

    /// Encode a [`MergeResult`] into the u64 packed return value.
    ///
    /// For `Synthesized`, a fresh payload buffer and an 8-byte
    /// `{ptr, len}` descriptor are allocated on the guest heap with
    /// layouts the host knows about, so the host's `mcgw_dealloc`
    /// calls free them correctly.
    #[must_use]
    pub fn encode_result(r: MergeResult) -> u64 {
        match r {
            MergeResult::Miss => 0,
            MergeResult::Winner(i) => ((i as u64) << 32) | 1,
            MergeResult::Synthesized(bytes) => encode_synthesized(&bytes),
        }
    }

    fn encode_synthesized(bytes: &[u8]) -> u64 {
        let len = bytes.len();
        let payload_layout = layout(len as u32, 1);
        let payload = unsafe { alloc(payload_layout) };
        if !bytes.is_empty() {
            unsafe {
                ptr::copy_nonoverlapping(bytes.as_ptr(), payload, len);
            }
        }
        let desc_layout = layout(8, 4);
        let desc = unsafe { alloc(desc_layout) };
        unsafe {
            ptr::write_unaligned(desc.cast::<u32>(), payload as usize as u32);
            ptr::write_unaligned(desc.add(4).cast::<u32>(), len as u32);
        }
        let desc_u32 = desc as usize as u64;
        (desc_u32 << 32) | 2
    }

    /// Pack a `&'static str` as `(ptr << 32) | len` for
    /// `mcgw_required_flags`. The bytes live in the module's data
    /// segment; the host reads them without freeing.
    #[inline]
    #[must_use]
    pub fn pack_static_str(s: &'static str) -> u64 {
        let b = s.as_bytes();
        ((b.as_ptr() as usize as u64) << 32) | (b.len() as u64)
    }
}
